### ISSUE TITLE
As a Wazzafak user, I would like to be able to browse jobs by proximity

### ISSUE THREAD

**Issue by ivan-1kh** [FACN8/Wazzafak#10]
- [x] Express server #1 - Serving User request sent from end and interact database (get&post)
- [x] React #8 - Minimal designed user interface (Userdata Applications, Vacancies)
- [x] Resources* #7 - structured resource folder with handling storage
- [x] User interface #3 - Minimal design
- [x] Database #2 - Handling select and insert requests
