### ISSUE TITLE
As a Wazzafak business-user I would like to easily access the applications for my listings

### ISSUE THREAD

**Issue by ivan-1kh** [FACN8/Wazzafak#12]
- [x] Express server #1 - Serving User request sent from end and interact database (get&post)
- [x] React #8 - Minimally designed required business interface - (Budata, Applicants, Vacancies)
- [x] Resources #7 - structured resource folder with handling storage
- [x] Business Interface #4 - minimal design
- [x] Database #2 - Handling select and insert requests
